var it =
    [{"name":"Technical It Support ","instructor":"James Bond","wholePrice":"$49","priceFraction":"98","stock":47,"star":4,"starCount":88,"img":"https://www.tutorialrepublic.com/lib/images/javascript-illustration.png","url":"https://www.tutorialrepublic.com/javascript-tutorial/","price":48.98},
{"name":"Learn Basic Networking System","instructor":"James Kond","wholePrice":"$49","priceFraction":"98","stock":47,"star":4,"starCount":88,"img":"https://miro.medium.com/max/3200/1*nBbb3oVqPH1g5Que9_VqbA.png","url":"https://medium.com/heuristics/electron-react-python-part-1-introduction-b228ccf8e889","price":48.98},
{"name":"Internet History and Security ","instructor":"James Hasil","wholePrice":"$49","priceFraction":"98","stock":47,"star":4,"starCount":88,"img":"https://cdn.eventfinda.co.nz/uploads/events/transformed/1219458-543438-34.jpg","url":"https://events.stuff.co.nz/auckland/2019/python-programming-language/auckland/te-atatu-peninsula","price":48.98},
{"name":"It Automation With Python","instructor":"James Kalil","wholePrice":"$49","priceFraction":"98","stock":47,"star":4,"starCount":88,"img":"https://cdn-media-1.freecodecamp.org/images/1*F8R-PEI9iVJ-sY3qFZemCg.png","url":"https://www.freecodecamp.org/news/what-is-an-api-in-english-please-b880a3214a82/","price":48.98},
{"name":"Operating System And Peripherals","instructor":"KA master","wholePrice":"$49","priceFraction":"98","stock":47,"star":4,"starCount":88,"img":"https://justfreewpthemes.com/wp-content/uploads/2019/05/WordPress-PHP-plugin.png","url":"https://justfreewpthemes.com/top-7-best-wordpress-php-plugin-for-your-site-in-2019/","price":48.98},
{"name":"Learn Programming With C","instructor":"James Bond","wholePrice":"$49","priceFraction":"98","stock":47,"star":4,"starCount":88,"img":"https://www.tutorialrepublic.com/lib/images/javascript-illustration.png","url":"https://www.tutorialrepublic.com/javascript-tutorial/","price":48.98},
{"name":"Learn Programming With Python","instructor":"James Kond","wholePrice":"$49","priceFraction":"98","stock":47,"star":4,"starCount":88,"img":"https://miro.medium.com/max/3200/1*nBbb3oVqPH1g5Que9_VqbA.png","url":"https://medium.com/heuristics/electron-react-python-part-1-introduction-b228ccf8e889","price":48.98},
{"name":"Learn C++ Basic For Competitive Programming ","instructor":"James Hasil","wholePrice":"$49","priceFraction":"98","stock":47,"star":4,"starCount":88,"img":"https://cdn.eventfinda.co.nz/uploads/events/transformed/1219458-543438-34.jpg","url":"https://events.stuff.co.nz/auckland/2019/python-programming-language/auckland/te-atatu-peninsula","price":48.98},
{"name":"Algorithm and Data Structure Part-1","instructor":"James Kalil","wholePrice":"$49","priceFraction":"98","stock":47,"star":4,"starCount":88,"img":"https://cdn-media-1.freecodecamp.org/images/1*F8R-PEI9iVJ-sY3qFZemCg.png","url":"https://www.freecodecamp.org/news/what-is-an-api-in-english-please-b880a3214a82/","price":48.98},
{"name":"Algorithm and Data Structure Part-2","instructor":"KA master","wholePrice":"$49","priceFraction":"98","stock":47,"star":4,"starCount":88,"img":"https://justfreewpthemes.com/wp-content/uploads/2019/05/WordPress-PHP-plugin.png","url":"https://justfreewpthemes.com/top-7-best-wordpress-php-plugin-for-your-site-in-2019/","price":48.98},
{"name":"Learn Javascript","instructor":"James Bond","wholePrice":"$49","priceFraction":"98","stock":47,"star":4,"starCount":88,"img":"https://www.tutorialrepublic.com/lib/images/javascript-illustration.png","url":"https://www.tutorialrepublic.com/javascript-tutorial/","price":48.98},
{"name":"Learn React With Python","instructor":"James Kond","wholePrice":"$49","priceFraction":"98","stock":47,"star":4,"starCount":88,"img":"https://miro.medium.com/max/3200/1*nBbb3oVqPH1g5Que9_VqbA.png","url":"https://medium.com/heuristics/electron-react-python-part-1-introduction-b228ccf8e889","price":48.98},
{"name":"Learn Python Basic For Web","instructor":"James Hasil","wholePrice":"$49","priceFraction":"98","stock":47,"star":4,"starCount":88,"img":"https://cdn.eventfinda.co.nz/uploads/events/transformed/1219458-543438-34.jpg","url":"https://events.stuff.co.nz/auckland/2019/python-programming-language/auckland/te-atatu-peninsula","price":48.98},
{"name":"API Basic with PHP","instructor":"James Kalil","wholePrice":"$49","priceFraction":"98","stock":47,"star":4,"starCount":88,"img":"https://cdn-media-1.freecodecamp.org/images/1*F8R-PEI9iVJ-sY3qFZemCg.png","url":"https://www.freecodecamp.org/news/what-is-an-api-in-english-please-b880a3214a82/","price":48.98},
{"name":"Learn PHP For Web","instructor":"KA master","wholePrice":"$49","priceFraction":"98","stock":47,"star":4,"starCount":88,"img":"https://justfreewpthemes.com/wp-content/uploads/2019/05/WordPress-PHP-plugin.png","url":"https://justfreewpthemes.com/top-7-best-wordpress-php-plugin-for-your-site-in-2019/","price":48.98}];

export default it;